### ISSUE TITLE
How to use this package when using dependency injection?

### ISSUE THREAD

**Issue by MikeAlhayek** [moozzyk/EFInteractiveViews#10]
I use Unity.Mvc to create IoC in my application. 

I register my DbContext as following

     Container.RegisterType<DataContext>(new PerRequestLifetimeManager());

How would I set the Set the view cache factory?

**Comment by moozzyk** [comment]
How big is your database? Because I have a feeling you don't need this package. 

TLDR;
I have not tried using it with unity by my guess would be that you would want to do this before you register the type in the container.

**Comment by MikeAlhayek** [comment]
My DbContext has about 200 `DbSet<>`

**Comment by moozzyk** [comment]
I don't know how much time it is taking to generate views right now but in that case you actually may see some noticeable improvements. Try putting it before you register the context in the DI container. If anything else uses the context before you register view cache factory it will be too late. The context that you pass to register is only there so to be able to access the mapping collection and register.
