### ISSUE TITLE
EF6.3 / NetStandard 2.1 Release

### ISSUE THREAD

**Issue by CZEMacLeod** [moozzyk/EFInteractiveViews#11]
I noticed that there are now EF6.3 / NS2.1 releases for EntityFramework.Cache and EntityFramework.CodeFirstStoreFunctions.
Would it be possible to get an updated version of this project too?
I did a quick check and it does appear to compile correctly multi-targeting with net40, net45 and netstandard2.1.

**Comment by issafram** [comment]
The project seems like its been stale for multiple years.
I would move on to something else if I was you.

**Comment by moozzyk** [comment]
It’s not stale. It’s complete.

**Comment by CZEMacLeod** [comment]
@moozzyk Certainly stable and works well. But now we are trying to migrate our codebases to support NETCore3.0 / NetStandard2.1 using EF6.3 which multi-targets net40, net45 and netstandard2.1. I believe your original code targeted net40 and net45. I would appreciate a netstandard2.1 build so I don't get restore errors for the package when targeting ns2.1.
I think you have done this for other packages you have released for EF6 already and just wandered if you would do this one too.
I did a quick conversion to SDK format project and compiled it and it seemed to work as expected...
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyTitle>InteractivePreGeneratedViews</AssemblyTitle>
    <Description>Interactive Pre-Generated Views for Entity Framework 6</Description>
    <Company>Pawel Kadluczka</Company>
    <Product>InteractivePreGeneratedViews</Product>
    <Copyright>Copyright ©  2013</Copyright>
    <TargetFrameworks>net40;net45;netstandard2.1</TargetFrameworks>
    <ProjectGuid>{AF712BBC-72CD-45AA-8452-E0CDE1CF2CA0}</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>InteractivePreGeneratedViews</RootNamespace>
    <AssemblyName>InteractivePreGeneratedViews</AssemblyName>
    <InternalsVisibleToEnabled Condition=" $(InternalsVisibleToEnabled) == ''">true</InternalsVisibleToEnabled>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <PackageId>EFInteractiveViews</PackageId>
    <Version>1.0.2</Version>
    <Authors>Pawel "moozzyk" Kadluczka</Authors>
    <Title>Interactive Pregenerated Views for Entity Framework 6</Title>
    <PackageLicenseExpression>MS-PL</PackageLicenseExpression>
    <!--<PackageLicenseUrl>https://efinteractiveviews.codeplex.com/license</PackageLicenseUrl>-->
    <PackageProjectUrl>https://github.com/moozzyk/EFInteractiveViews</PackageProjectUrl>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageTags>EF6;EF;entity-framework;EntityFramework;Entity Framework;Pregenerated Views;moozzyk;blog.3d-logic.com</PackageTags>
  </PropertyGroup>

  <PropertyGroup>
    <DefineConstants Condition=" '$(InternalsVisibleToEnabled)'">$(DefineConstants);INTERNALSVISIBLETOENABLED</DefineConstants>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' != 'netstandard2.1'">
    <PackageReference Include="EntityFramework" Version="[6.0.0,7.0)" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
    <PackageReference Include="EntityFramework" Version="[6.3.0,7.0)" />
  </ItemGroup>
  <Target Name="CreatePackage">
    <Error Text="KeyFile parameter not specified (/p:KeyFile=MyKey.snk)" Condition=" '$(KeyFile)' == ''" />
    <PropertyGroup>
      <Configuration>Release</Configuration>
    </PropertyGroup>
    <MSBuild Projects="$(MSBuildProjectFile)" Targets="Clean,Pack" Properties="InternalsVisibleToEnabled=false;SignAssembly=true;AssemblyOriginatorKeyFile=$(KeyFile);Configuration=$(Configuration)" BuildInParallel="$(BuildInParallel)" />
  </Target>
</Project>
```

**Comment by moozzyk** [comment]
@CZEMacLeod - how big is your model (i.e. how many entities) and how much improvement do you see when you use this package?

**Comment by CZEMacLeod** [comment]
@moozzyk We have 20+ data contexts each with 20 to 200 models and inheritance. As we usually only work on 1 module, and often not even the DAL assemblies, using this shaves 30 to 60 seconds plus from the startup time, and/or the first access time for each DAL in use which makes the apps more responsive on the web when the shutdown and spin up (for low use) or whilst developing.
On Azure I use the temp drive to dump the models, and on my dev machine use an SSD or RAM drive.

**Comment by moozzyk** [comment]
Thanks for the details. In that case I will look into adding support for
netstandard. Stay tuned.

**Comment by moozzyk** [comment]
8cda367cf0b722cc8e89a1bff917fe918b1f5728

**Comment by moozzyk** [comment]
Today I uploaded 1.1.0 version of the package to NuGet (https://www.nuget.org/packages/EFInteractiveViews/1.1.0) which adds support for .NET Standard 2.1
