### ISSUE TITLE
Change DbContext to IObjectContextAdapter in InteractiveViews.SetViewCacheFactory

### ISSUE THREAD

**Issue by AlexeyBoiko** [moozzyk/EFInteractiveViews#12]
Hello, (not an issue - don't know where to say it)
Thank you for library.

Please change DbContext to IObjectContextAdapter in InteractiveViews.SetViewCacheFactory

`public static void SetViewCacheFactory(IObjectContextAdapter context, DbMappingViewCacheFactory viewCacheFactory)`

I my case I have to fork just for that, as we use custom dbContext implementation.

Thank you.

**Comment by moozzyk** [comment]
What do you mean by “custom dbContext implementation”?

**Comment by moozzyk** [comment]
Regardless - you can just pass `ObjectContext` using the other overload: 
https://github.com/moozzyk/EFInteractiveViews/blob/8cda367cf0b722cc8e89a1bff917fe918b1f5728/src/InteractivePreGeneratedViews/InteractiveViews.cs#L64

**Comment by AlexeyBoiko** [comment]
>What do you mean by “custom dbContext implementation”?

Our context do not inherit DbContext.

>you can just pass ObjectContext using the other overload

Thank you
