### ISSUE TITLE
Create schema if it's missing

### ISSUE THREAD

**Issue by RaringCoder** [moozzyk/EFInteractiveViews#8]
If you specify a schema for the `SqlServerViewCacheFactory` it doesn't appear to work if the schema is missing. A simple addition to the context `modelBuilder.HasDefaultSchema` can fix this.

**Comment by moozzyk** [comment]
Can you show me the error (including stack trace)?

**Comment by RaringCoder** [comment]
I've not got the code anymore. It's very easy to reproduce though, just specify a non-"dbo" schema against a database where that schema doesn't exist and it won't work due to the code definition for the model not stipulating the schema via `HasSchema`.
