### ISSUE TITLE
Creating views in SQL server not working with Azure

### ISSUE THREAD

**Issue by ddivita** [moozzyk/EFInteractiveViews#9]
Creating the xml in SQL works with the standard version of SQL server (2017). When trying to create the view in azure the table does not get created. I confirmed the connection string and the user is an SA. I am not sure if this is unique to our environment and wanted to ask if anyone else has this same issue.

**Comment by ddivita** [comment]
Turn out it was a permission issue. the account we thought was being used for app services and the sql contention was not what we had thought.

**Comment by moozzyk** [comment]
I am glad you were able to find what the issue was!
